"""add registration applications

Revision ID: 8a20dac1bf7a
Revises: a12a0d5e0a8e
Create Date: 2026-09-27 18:29:21.492154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a20dac1bf7a'
down_revision: Union[str, Sequence[str], None] = 'a12a0d5e0a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_delete_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_applications_created_at'), 'registration_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_registration_applications_document_delete_after'), 'registration_applications', ['document_delete_after'], unique=False)
    op.create_index(op.f('ix_registration_applications_email'), 'registration_applications', ['email'], unique=False)
    op.create_index(op.f('ix_registration_applications_reviewed_at'), 'registration_applications', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_registration_applications_reviewed_by'), 'registration_applications', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_registration_applications_school_name'), 'registration_applications', ['school_name'], unique=False)
    op.create_index(op.f('ix_registration_applications_status'), 'registration_applications', ['status'], unique=False)
    op.create_index(op.f('ix_registration_applications_username'), 'registration_applications', ['username'], unique=False)
    op.create_table('registration_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['registration_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_documents_application_id'), 'registration_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_registration_documents_deleted_at'), 'registration_documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_registration_documents_sha256'), 'registration_documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_registration_documents_storage_path'), 'registration_documents', ['storage_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_documents_storage_path'), table_name='registration_documents')
    op.drop_index(op.f('ix_registration_documents_sha256'), table_name='registration_documents')
    op.drop_index(op.f('ix_registration_documents_deleted_at'), table_name='registration_documents')
    op.drop_index(op.f('ix_registration_documents_application_id'), table_name='registration_documents')
    op.drop_table('registration_documents')
    op.drop_index(op.f('ix_registration_applications_username'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_status'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_school_name'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_reviewed_by'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_reviewed_at'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_email'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_document_delete_after'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_created_at'), table_name='registration_applications')
    op.drop_table('registration_applications')
    # ### end Alembic commands ###
